env:
  commonjs: true
  es2021: true
  node: true
globals: {
        'browser': true,
        'expect': true,
        '$': true,
        '$$': true
    }
extends:
 - eslint:recommended
parser:
  '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelOptions: { plugins: ["@babel/plugin-syntax-class-properties"] }
plugins:
  - import
rules:
  import/no-unresolved: [2, {commonjs: true, amd: true, caseSensitive: true}]
  import/extensions: [2, {"js": "always"}]
