name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npx wdio wdio.conf.js --squad=Diamondere
        - uses: actions/upload-artifact@v1
          with:
            name: report
            path: ./reports/html